"use client";

import React, { createContext, useContext, useState, useEffect, useRef } from "react";

export type CursorState =
  | "default"
  | "hover"
  | "link"
  | "button"
  | "card"
  | "input"
  | "upload"
  | "loading"
  | "success"
  | "error"
  | "click";

interface InteractionContextType {
  cursorState: CursorState;
  cursorLabel: string;
  mousePosition: { x: number; y: number };
  isHovering: boolean;
  isDesktop: boolean;
  setCursorState: (state: CursorState, label?: string) => void;
  triggerSuccess: (durationMs?: number) => void;
  triggerError: (durationMs?: number) => void;
  triggerLoading: (durationMs?: number) => void;
}

const InteractionContext = createContext<InteractionContextType | undefined>(undefined);

export function InteractionProvider({ children }: { children: React.ReactNode }) {
  const [cursorState, setCursorStateState] = useState<CursorState>("default");
  const [cursorLabel, setCursorLabel] = useState("");
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  const [isHovering, setIsHovering] = useState(false);
  const [isDesktop, setIsDesktop] = useState(false);

  const stateTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  const setCursorState = (state: CursorState, label = "") => {
    // Clear any pending temporary overrides
    if (stateTimeoutRef.current) {
      clearTimeout(stateTimeoutRef.current);
      stateTimeoutRef.current = null;
    }
    setCursorStateState(state);
    setCursorLabel(label);
  };

  const triggerSuccess = (durationMs = 1200) => {
    setCursorState("success", "Success!");
    stateTimeoutRef.current = setTimeout(() => {
      setCursorStateState("default");
      setCursorLabel("");
    }, durationMs);
  };

  const triggerError = (durationMs = 1500) => {
    setCursorState("error", "Error!");
    stateTimeoutRef.current = setTimeout(() => {
      setCursorStateState("default");
      setCursorLabel("");
    }, durationMs);
  };

  const triggerLoading = (durationMs = 2000) => {
    setCursorState("loading", "Processing");
    stateTimeoutRef.current = setTimeout(() => {
      setCursorStateState("default");
      setCursorLabel("");
    }, durationMs);
  };

  useEffect(() => {
    let lastTouchTime = 0;
    let animationFrameId: number;

    const handleTouchStart = (e: TouchEvent) => {
      lastTouchTime = Date.now();
      const target = e.target as HTMLElement;
      if (!target) return;

      const interactiveEl = target.closest("a, button, [role='button'], [data-cursor]");
      if (!interactiveEl) return;

      // Create ripple element inside target bounding box
      const rect = interactiveEl.getBoundingClientRect();
      const touch = e.touches[0];
      const x = touch.clientX - rect.left;
      const y = touch.clientY - rect.top;

      const ripple = document.createElement("span");
      ripple.className = "tap-ripple";
      ripple.style.left = `${x}px`;
      ripple.style.top = `${y}px`;
      ripple.style.width = ripple.style.height = `${Math.max(rect.width, rect.height)}px`;

      // Make sure container is relatively positioned
      const originalPosition = window.getComputedStyle(interactiveEl).position;
      if (originalPosition === "static") {
        (interactiveEl as HTMLElement).style.position = "relative";
      }
      
      // Overflow hidden setup
      const originalOverflow = window.getComputedStyle(interactiveEl).overflow;
      if (originalOverflow !== "hidden") {
        (interactiveEl as HTMLElement).style.overflow = "hidden";
      }

      interactiveEl.appendChild(ripple);

      setTimeout(() => {
        ripple.remove();
      }, 600);
    };

    const handleMouseMove = (e: MouseEvent) => {
      // Ignore mouse moves generated by touch taps
      if (Date.now() - lastTouchTime < 500) return;

      if (!isDesktop) {
        setIsDesktop(true);
        document.body.classList.add("toolchi-cursor-active");
      }
      if (!isHovering) {
        setIsHovering(true);
      }
      
      cancelAnimationFrame(animationFrameId);
      animationFrameId = requestAnimationFrame(() => {
        setMousePosition({ x: e.clientX, y: e.clientY });
      });
    };

    const handleMouseLeave = () => {
      setIsHovering(false);
    };

    const handleMouseDown = () => {
      if (Date.now() - lastTouchTime < 500) return;
      setCursorStateState("click");
    };

    const handleMouseUp = (e: MouseEvent) => {
      if (Date.now() - lastTouchTime < 500) return;
      const target = e.target as HTMLElement;
      if (target) {
        const interactiveEl = target.closest("[data-cursor], a, button, input, textarea, select, [role='button']");
        if (interactiveEl) {
          const customState = interactiveEl.getAttribute("data-cursor") as CursorState;
          setCursorStateState(customState || "hover");
        } else {
          setCursorStateState("default");
        }
      } else {
        setCursorStateState("default");
      }
    };

    const handleMouseOver = (e: MouseEvent) => {
      if (Date.now() - lastTouchTime < 500) return;
      const target = e.target as HTMLElement;
      if (!target) return;

      const interactiveEl = target.closest("[data-cursor], a, button, input, textarea, select, [role='button']");
      if (!interactiveEl) {
        setCursorStateState("default");
        setCursorLabel("");
        return;
      }

      const customState = interactiveEl.getAttribute("data-cursor") as CursorState;
      const customLabel = interactiveEl.getAttribute("data-cursor-label") || "";

      if (customState) {
        setCursorStateState(customState);
        setCursorLabel(customLabel);
      } else {
        const tagName = interactiveEl.tagName.toLowerCase();
        if (tagName === "a") {
          setCursorStateState("link");
        } else if (tagName === "button" || interactiveEl.getAttribute("role") === "button") {
          setCursorStateState("button");
        } else if (tagName === "input" || tagName === "textarea") {
          setCursorStateState("input");
        } else {
          setCursorStateState("hover");
        }
      }
    };

    document.addEventListener("touchstart", handleTouchStart, { passive: true });
    document.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("mouseleave", handleMouseLeave);
    document.addEventListener("mouseover", handleMouseOver);
    document.addEventListener("mousedown", handleMouseDown);
    document.addEventListener("mouseup", handleMouseUp);

    return () => {
      cancelAnimationFrame(animationFrameId);
      document.body.classList.remove("toolchi-cursor-active");
      document.removeEventListener("touchstart", handleTouchStart);
      document.removeEventListener("mousemove", handleMouseMove);
      document.removeEventListener("mouseleave", handleMouseLeave);
      document.removeEventListener("mouseover", handleMouseOver);
      document.removeEventListener("mousedown", handleMouseDown);
      document.removeEventListener("mouseup", handleMouseUp);
    };
  }, [isHovering, isDesktop]);

  return (
    <InteractionContext.Provider
      value={{
        cursorState,
        cursorLabel,
        mousePosition,
        isHovering,
        isDesktop,
        setCursorState,
        triggerSuccess,
        triggerError,
        triggerLoading,
      }}
    >
      {children}
    </InteractionContext.Provider>
  );
}

export function useInteraction() {
  const context = useContext(InteractionContext);
  if (!context) {
    throw new Error("useInteraction must be used within an InteractionProvider");
  }
  return context;
}
